name: common
description: Common utilities and helpers for the Flutter app
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ^3.29.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.2
  simple_logger: ^1.10.0
  intl: ^0.20.2
  dio: ^5.4.1
  crypto: ^3.0.3
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5

resolution: workspace 
