name: flutter_app_template
repository: https://github.com/tegueneeeee/flutter_app_template
sdkPath: .fvm/flutter_sdk

packages:
  - apps/*
  - packages/*

command:
  bootstrap:
    runPubGetInParallel: true
    hooks:
      post: |
        melos exec --flutter --dir-exists=lib/l10n -- "flutter gen-l10n"
  clean:
    hooks:
      post: |
        melos exec --flutter -- "flutter clean"
        melos exec --flutter --file-exists="ios/Podfile.lock" -- "cd ios && rm Podfile.lock"
  version:
    branch: main

scripts:
  upgrade:
    run: |
      melos exec -- \
        "flutter pub upgrade --major-versions && flutter pub upgrade"
    description: Upgrade all packages to the latest version
    packageFilters:
      flutter: true
      dirExists: lib

  analyze:
    run: |
      melos run analyze:dart --no-select
      melos run analyze:flutter --no-select
      melos run analyze:custom_lint --no-select
    description: Run all analyze.
    packageFilters:
      dirExists: lib

  analyze:dart:
    run: |
      melos exec -- \
        dart analyze . --fatal-infos
    description: Run dart analyze.
    packageFilters:
      flutter: false
      dirExists: lib

  analyze:flutter:
    run: |
      melos exec --flutter -- \
        flutter analyze . --fatal-infos
    description: Run flutter analyze.
    packageFilters:
      flutter: true
      dirExists: lib

  analyze:custom_lint:
    run: |
      melos exec -- \
        dart run custom_lint
    description: Run custom lint.
    packageFilters:
      dirExists: lib
      dependsOn: "custom_lint"

  format:
    run: |
      melos exec -- \
        dart format lib test
    description: Run format.
    packageFilters:
      flutter: true
      dirExists: [lib, test]

  format:ci:
    run: |
      melos exec -- \
        dart format --set-exit-if-changed lib test
    description: Run format ci.
    packageFilters:
      flutter: true
      dirExists: [lib, test]

  fix:
    run: |
      melos exec -- \
        dart fix --apply lib
    description: Run dart fix.
    packageFilters:
      dirExists: lib

  gen:
    run: |
      melos exec -c 1 -- \
        dart run build_runner build --delete-conflicting-outputs
    description: Run generate code.
    packageFilters:
      dirExists: lib
      dependsOn: "build_runner"

  gen:watch:
    run: |
      melos exec -c 1 -- \
        dart run build_runner watch --delete-conflicting-outputs
    description: Watch and run generate code.
    packageFilters:
      dirExists: lib
      dependsOn: "build_runner"

  test:
    run: |
      melos exec --fail-fast -- \
        flutter test
    description: Run flutter test.
    packageFilters:
      flutter: true
      dirExists: test

  test:ci:
    run: |
      melos exec --fail-fast -- \
        flutter test --coverage
    description: Run flutter test ci.
    packageFilters:
      flutter: true
      dirExists: test

  pod:
    run: |
      melos run pod:ios --no-select
    description: Run all pod install.

  pod:ios:
    run: |
      melos exec -- \
        cd ios && pod install
    description: Run pod install for ios.
    packageFilters:
      dirExists: [lib, ios]
      fileExists: ios/Podfile

  build:android:prod:
    run: |
      melos exec -c 1 -- \
        flutter build appbundle --dart-define-from-file=dart_defines/prod.env
    description: Build the Appbundle for the production app.
    packageFilters:
      flutter: true
      dirExists: [lib, android]

  build:ios:prod:
    run: |
      melos exec -c 1 -- \
        flutter build ipa --dart-define-from-file=dart_defines/prod.env --export-options-plist="ios/prod/ExportOptions.plist"
    description: Build the IPA for the production app.
    packageFilters:
      flutter: true
      dirExists: [lib, ios]
