name: flutter_app_template
sdkPath: .fvm/flutter_sdk

packages:
  - apps/*
  - packages/*

command:
  bootstrap:
    environment:
      sdk: ^3.3.3
      flutter: ^3.19.5
    dependencies:
      hooks_riverpod: ^2.5.1
      flutter_hooks: ^0.20.5
      freezed_annotation: ^2.4.1
      json_annotation: ^4.8.1
      riverpod_annotation: ^2.3.5
    dev_dependencies:
      build_runner: ^2.4.9
      custom_lint: ^0.6.4
      freezed: ^2.5.0
      json_serializable: ^6.7.1
      riverpod_generator: ^2.4.0
      riverpod_lint: ^2.3.10
      pedantic_mono: ^1.26.0


scripts:
  report_test:
    exec: flutter test --no-pub --machine > test_report.log
    packageFilters:
      flutter: true

  format:
    exec: bash "$MELOS_ROOT_PATH/scripts/format.sh"
    packageFilters:
      flutter: true

  upgrade:
    run: |
      melos exec -- \
        "flutter pub upgrade --major-versions && flutter pub upgrade"
    description: Upgrade all packages to the latest version
    packageFilters:
      flutter: true
      dirExists: lib

  analyze:
    run: |
      melos run analyze:dart --no-select
      melos run analyze:flutter --no-select
      melos run analyze:custom_lint --no-select
    description: Run all analyze.
    packageFilters:
      dirExists: lib

  analyze:dart:
    run: |
      melos exec -- \
        dart analyze . --fatal-infos
    description: Run dart analyze.
    packageFilters:
      flutter: false
      dirExists: lib

  analyze:flutter:
    run: |
      melos exec --flutter -- \
        flutter analyze . --fatal-infos
    description: Run flutter analyze.
    packageFilters:
      flutter: true
      dirExists: lib

  analyze:custom_lint:
    run: |
      melos exec -- \
        dart run custom_lint
    description: Run custom lint.
    packageFilters:
      dirExists: lib
      dependsOn: "custom_lint"

  fix:
    run: |
      melos exec -- \
        dart fix --apply lib
    description: Run dart fix.
    packageFilters:
      dirExists: lib

  gen:
    run: |
      melos exec -c 1 -- \
        dart run build_runner build --delete-conflicting-outputs
    description: Run generate code.
    packageFilters:
      dirExists: lib
      dependsOn: "build_runner"

  gen:watch:
    run: |
      melos exec -c 1 -- \
        dart run build_runner watch --delete-conflicting-outputs
    description: Watch and run generate code.
    packageFilters:
      dirExists: lib
      dependsOn: "build_runner"

  pod:
    run: |
      melos run pod:ios --no-select
    description: Run all pod install.

  pod:ios:
    run: |
      melos exec -- \
        cd ios && pod install
    description: Run pod install for ios.
    packageFilters:
      dirExists: [lib, ios]
      fileExists: ios/Podfile

  build:android:prod:
    run: |
      melos exec -c 1 -- \
        flutter build appbundle --dart-define-from-file=dart_defines/prod.env
    description: Build the Appbundle for the production app.
    packageFilters:
      flutter: true
      dirExists: [lib, android]

  build:ios:prod:
    run: |
      melos exec -c 1 -- \
        flutter build ipa --dart-define-from-file=dart_defines/prod.env --export-options-plist="ios/prod/ExportOptions.plist"
    description: Build the IPA for the production app.
    packageFilters:
      flutter: true
      dirExists: [lib, ios]
