name: flutter_app_template_workspace
environment:
  sdk: ^3.7.2

workspace:
  # apps
  - apps/app
  # - apps/catalog
  # packages
  - packages/core
  - packages/designsystem
  # features
  - packages/features/webview
  - packages/features/remote_config
  # shared
  - packages/shared/common
  - packages/shared/config
  - packages/shared/dependencies
  - packages/shared/i18n

dev_dependencies:
  mason_cli: ^0.1.2
  melos: ^7.0.0-dev.7

melos:
  sdkPath: .fvm/flutter_sdk

  command:
    bootstrap:
      environment:
        sdk: ^3.7.2
        flutter: ^3.29.2
      dependencies:
        flutter_hooks: ^0.21.2
        flutter_riverpod: ^2.6.1
        freezed_annotation: ^3.0.0
        hooks_riverpod: ^2.6.1
        intl: ^0.20.2
        json_annotation: ^4.9.0
        go_router: ^14.8.1
      dev_dependencies:
        build_runner: ^2.4.15
        custom_lint: ^0.7.5
        freezed: ^3.0.4
        json_serializable: ^6.9.4
        riverpod_generator: ^2.6.5
        riverpod_lint: ^2.6.5
        test: ^1.25.15
        flutter_gen_runner: ^5.10.0
      hooks:
      #  post: melos run bootstrap:post

  scripts:
    bootstrap:post:
      description: bootstrap post hooks
      steps:
        - gen:labeler
        - gen:labels

    fix:
      description:

    fix:custom:
      description:

    gen:
      description: Code generation using build_runner
      run: dart run build_runner build -d
      exec:
        orderDependents: true
      packageFilters:
        dependsOn: build_runner
    
    generate-env:
      description: Run build_runner in all of the packages that depends on it.
      run: dart run build_runner build -d
      exec:
        orderDependents: true
      packageFilters:
        dependsOn: envied_generator

    test:
      description: Run tests with coverage and random ordering
      run: flutter test
      exec:
        concurrency: 1
      packageFilters:
        dependsOn: flutter_test
        dirExists: test
        
    # I18n specific scripts
    gen:i18n:
      description: Generate internationalization files
      run: dart run build_runner build -d
      exec:
        concurrency: 1
      packageFilters:
        scope: i18n
        dependsOn: slang_build_runner
        
    gen:i18n:watch:
      description: Watch for changes and regenerate internationalization files
      run: dart run build_runner watch -d
      exec:
        concurrency: 1
      packageFilters:
        scope: i18n
        dependsOn: slang_build_runner
        
    i18n:analyze:
      description: Analyze translations for missing entries
      run: dart run build_runner build -d --define slang_build_runner:analyze=true
      exec:
        concurrency: 1
      packageFilters:
        scope: i18n
        dependsOn: slang_build_runner
