name: features_webview
description: "This package provides webview features."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ^3.29.2

resolution: workspace

dependencies:
  core:
    path: ../../core
  designsystem:
    path: ../../designsystem
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  shared_dependencies:
    path: ../../shared/dependencies
  webview_flutter: ^4.10.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
