name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["feature", "triage"]
body:
  - type: checkboxes
    attributes:
      label: "🔍 Issue check"
      options:
        - label: "I have searched open and closed issues for duplicates"
          required: true
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Please provide a clear and concise description of what the motivation for the feature is."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: "Proposal"
      description: "Please provide a clear and concise description of what the feature should do."
    validations:
      required: true
