name: Improve Request
description: Suggest an improvement for this project
title: "[Improve]: "
labels: ["improve", "triage"]
body:
  - type: checkboxes
    attributes:
      label: "🔍 Issue check"
      options:
        - label: "I have searched open and closed issues for duplicates"
          required: true
  - type: textarea
    id: context
    attributes:
      label: "Background"
      description: "Please provide a clear and concise description of what the improvement is."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: "Details"
      description: "Please provide a clear and concise description of what the improvement should do."
    validations:
      required: false
  - type: textarea
    id: env
    attributes:
      label: "Environment"
      description: "Please provide details about the environment you experienced the improvement in."
      value: |
        - Commit Hash: ''
        - Platform: iOS 17.2.1, Android 14 Api level 34
        - Version: 1.0.0
      render: Markdown
    validations:
      required: true
