include: package:very_good_analysis/analysis_options.7.0.0.yaml
    
analyzer:
  plugins:
    # https://riverpod.dev/docs/introduction/getting_started#enabling-riverpod_lintcustom_lint
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    public_member_api_docs: ignore
    use_setters_to_change_properties: ignore
    invalid_annotation_target: ignore
