targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          include:
            - lib/{repositories,**/repositories}/**.dart
            - lib/{use_cases,**/use_cases}/**.dart
            - lib/**/*_page.dart
      freezed:
        # https://github.com/dart-lang/build/blob/master/docs/faq.md#how-do-i-avoid-running-builders-on-unnecessary-inputs
        generate_for:
          include:
            - lib/{models,**/models}/**.dart
      # https://github.com/google/json_serializable.dart/tree/master/json_serializable#build-configuration
      json_serializable:
        generate_for:
          include:
            - lib/{models,**/models}/**.dart
        options:
          field_rename: snake
          checked: true
      # https://github.com/dart-lang/source_gen#ignore_for_file
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - duplicate_ignore
