name: core
description: This is package provides core.
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ^3.29.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  package_info_plus: ^8.3.0
  riverpod_annotation: ^2.6.1
  shared_dependencies:
    path: ../shared/dependencies
  shared_preferences: ^2.5.3
  simple_logger: ^1.10.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^7.0.0
