name: designsystem
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.3.3
  flutter: ^3.19.5

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.26.0

flutter:
  uses-material-design: true
