name: Create issues at initialization
description: Create Github issues based on initialization

inputs:
  language:
    description: The language of the issue to create.
    default: en

runs:
  using: composite
  steps:
    # https://github.com/marketplace/actions/create-issue-from-file
    - uses: peter-evans/create-issue-from-file@v5.0.1
      with:
        title: "[Initial Setup] Configure Automatic Reviewer Assignment for Pull Requests"
        content-filepath: .github/initialization/${{ inputs.language }}/GITHUB_AUTO_ASSIGNMENT.md
        labels: initialization

    # https://github.com/marketplace/actions/create-issue-from-file
    - uses: peter-evans/create-issue-from-file@v5.0.1
      with:
        title: "[Initial Setup] Icon Configuration"
        content-filepath: .github/initialization/${{ inputs.language }}/ABOUT_ICON.md
        labels: initialization

    # https://github.com/marketplace/actions/create-issue-from-file
    - uses: peter-evans/create-issue-from-file@v5.0.1
      with:
        title: "[Initial Setup] Rename Application ID"
        content-filepath: .github/initialization/${{ inputs.language }}/RENAME_APPLICATION_ID.md
        labels: initialization

    # https://github.com/marketplace/actions/create-issue-from-file
    - uses: peter-evans/create-issue-from-file@v5.0.1
      with:
        title: "[Optional Initial Setup] Splash Screen Configuration"
        content-filepath: .github/initialization/${{ inputs.language }}/SPLASH_SCREEN.md
        labels: | 
          initialization
          optional


    # https://github.com/marketplace/actions/create-issue-from-file
    - uses: peter-evans/create-issue-from-file@v5.0.1
      with:
        title: "[Optional Initial Setup] Configure Deployment Workflow in Pull Requests"
        content-filepath: .github/initialization/${{ inputs.language }}/FIREBASE_HOSTING_PREVIEW.md
        labels: |
          initialization
          optional
