targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          include:
            - lib/**/*_page.dart
            - lib/**/*_notifier.dart
            - lib/app_startup.dart
            - lib/router/router.dart
