name: flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.2.3
  flutter: ^3.16.4

dependencies:
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  gap: ^3.0.1
  go_router: ^13.0.0
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.0
  mocktail: ^1.0.2
  pedantic_mono: ^1.25.0
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter_gen:
  enabled: true
  output: lib/core/gen
  line_length: 80
  assets:
    output:
      style: dot-delimiter

flutter_launcher_icons:
  android: true
  ios: true

flutter:
  uses-material-design: true
