name: flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ^3.29.2

resolution: workspace

dependencies:
  core:
    path: ../../packages/cores/core
  designsystem:
    path: ../../packages/cores/designsystem
  features_remote_config:
    path: ../../packages/features/remote_config
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  go_router: ^14.8.1
  package_info_plus: ^8.3.0
  path: ^1.9.1
  riverpod_annotation: ^2.3.5
  shared_config:
    path: ../../packages/shared/config
  shared_dependencies:
    path: ../../packages/shared/dependencies
  shared_preferences: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  go_router_builder: ^2.8.2
  mocktail: ^1.0.2
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^7.0.0

flutter_launcher_icons:
  android: true
  ios: true

flutter:
  uses-material-design: true
