name: flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ^3.29.2

resolution: workspace

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  gap: ^3.0.1
  go_router: ^14.8.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.0
  mocktail: ^1.0.2
  pedantic_mono: ^1.26.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter_gen:
  enabled: true
  output: lib/core/gen
  line_length: 80
  assets:
    output:
      style: dot-delimiter

flutter_launcher_icons:
  android: true
  ios: true

flutter:
  uses-material-design: true
