name: features_remote_config
description: "This package provides remote_config features."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ^3.29.2

resolution: workspace

dependencies:
  core:
    path: ../../cores/core
  designsystem:
    path: ../../cores/designsystem
  firebase_remote_config: ^4.3.8
  flutter:
    sdk: flutter
  shared_config:
    path: ../../shared/config
  shared_dependencies:
    path: ../../shared/dependencies

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^7.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/remote_config_fallback.json
