name: Auto Assign

on:
  pull_request:
    types: [ opened, ready_for_review ]

permissions:
  pull-requests: write

jobs:
  count-reviewers:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    outputs:
      count: ${{ steps.extract.outputs.count }}
    steps:
      - name: Extract the number of reviewers
        id: extract
        run: |
          # https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=opened#pull_request
          # https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=ready_for_review#pull_request
          reviewers_count=$(jq '.pull_request.requested_reviewers | length' < "${{ github.event_path }}")
          echo "count=${reviewers_count}" >> "$GITHUB_OUTPUT"

  request-reviews:
    needs: count-reviewers
    if: needs.count-reviewers.outputs.count == '0'
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: Generate a token
        id: app-token
        uses: actions/create-github-app-token@v2.0.2
        with:
          app_id: ${{ secrets.APP_ID_OF_REVIEW_REQUESTER }}
          private_key: ${{ secrets.PRIVATE_KEY_OF_REVIEW_REQUESTER }}

      - name: Request reviewer
        env:
          REVIEWERS: ${{ vars.REVIEWERS }}
          TEAM_REVIEWERS: ${{ vars.TEAM_REVIEWERS }}
        run: |
          reviewers=$(jq -R 'split(",")' <<< "${REVIEWERS:-}" | jq 'map(select(length > 0))')
          team_reviewers=$(jq -R 'split(",")' <<< "${TEAM_REVIEWERS:-}" | jq 'map(select(length > 0))')
          # https://docs.github.com/ja/rest/pulls/review-requests?apiVersion=2022-11-28#request-reviewers-for-a-pull-request
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers" \
            -d "{ \"reviewers\": ${reviewers}, \"team_reviewers\": ${team_reviewers} }"

  request-assignees:
    needs:
      - count-reviewers
      - request-reviewers
    if: always()
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      # https://github.com/marketplace/actions/review-assign-action
      - name: Request assignees
        uses: hkusu/review-assign-action@v1.4.0
        with:
          assignees: ${{ github.actor }}
          ready-comment: 'Ready for review :rocket:'
