name: Initialization

on:
  push:
    branches:
      - main

jobs:
  condition:
    runs-on: ubuntu-22.04
    outputs:
      execute: ${{ steps.condition.outputs.execute }}
    steps:
      - id: condition
        run: |
          if [[ "${{ github.event.repository.name }}" != "flutter_app_template" ]]; then
            echo "execute=true" >> "$GITHUB_OUTPUT"
          else
            echo "execute=false" >> "$GITHUB_OUTPUT"
          fi

  create-issues:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      issues: write
    needs: condition
    if: needs.condition.outputs.execute == 'true'
    timeout-minutes: 10
    steps:
      # https://github.com/actions/checkout
      - name: Fetch sources
        uses: actions/checkout@v4.2.2

      - name: Create Issues at Initialization
        uses: ./.github/actions/create-issue-at-initialization

  cleanup:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    needs:
      - condition
      - create-issues
    if: needs.condition.outputs.execute == 'true'
    timeout-minutes: 10
    steps:
      # https://github.com/actions/checkout
      - name: Fetch sources
        uses: actions/checkout@v4.2.2

      - name: Remove unnecessary files
        uses: ./.github/actions/remove-unnecessary-files

      - name: Fill project name
        uses: ./.github/actions/fill-project-name

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Template cleanup"

      # https://github.com/ad-m/github-push-action
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/actions/checkout
      - name: Check out latest state of original repository
        uses: actions/checkout@v4.2.2
