name: Check markdown files

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # https://github.com/DavidAnson/markdownlint-cli2-action
      - name: Check markdown
        uses: DavidAnson/markdownlint-cli2-action@v19.1.0
