name: Check generated code is latest

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      # https://github.com/actions/cache
      - name: Cache build runner
        id: cache-build-runner
        uses: actions/cache@v4.2.3
        with:
          path: |
            **/.dart_tool/build
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}

      - name: Regenerate code
        run: melos run gen --no-select

      - name: Check difference
        run: |
          git add -N .
          git diff --name-only --exit-code
